spring:
  datasource:
    url: jdbc:postgresql://db:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

logging:
  level:
    liquibase: INFO
    org.springframework.jdbc: DEBUG