CREATE TABLE IF NOT EXISTS hotels (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    city VARCHAR(255) NOT NULL,
    country VARCHAR(255) NOT NULL,
    address VARCHAR(255) NOT NULL,
    managerId BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    rating DECIMAL(2,1) DEFAULT 0.0,
    isDeleted BOOLEAN NOT NULL DEFAULT FALSE,

    CONSTRAINT fk_hotel_manager FOREIGN KEY (managerId) REFERENCES users(id)
);