CREATE TABLE IF NOT EXISTS hotels (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    city VARCHAR(255) NOT NULL,
    country VARCHAR(255) NOT NULL,
    address VARCHAR(255) NOT NULL,
    rating INTEGER NOT NULL CHECK (rating BETWEEN 1 AND 5),
    managerId BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    isDeleted BOOLEAN NOT NULL DEFAULT FALSE
);