CREATE TABLE IF NOT EXISTS bookings (
    id BIGSERIAL PRIMARY KEY,
    userId BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    roomId BIGINT NOT NULL REFERENCES rooms(id) ON DELETE RESTRICT,
    checkInDate DATE NOT NULL,
    checkOutDate DATE NOT NULL CHECK (checkOutDate > checkInDate),
    totalPrice DECIMAL(10,2) NOT NULL CHECK (totalPrice > 0),
    status VARCHAR(10) NOT NULL DEFAULT 'CREATED' CHECK(status IN ('CREATED', 'CONFIRMED', 'CANCELLED', 'COMPLETED')),
    isDeleted BOOLEAN NOT NULL DEFAULT FALSE
);