CREATE TABLE IF NOT EXISTS loyalty_programs (
    id BIGSERIAL PRIMARY KEY,
    userId BIGINT NOT NULL UNIQUE,
    totalPoints INTEGER NOT NULL DEFAULT 0,
    tier VARCHAR(10) NOT NULL DEFAULT 'BRONZE' CHECK(tier IN ('BRONZE', 'SILVER', 'GOLD', 'PLATINUM')),
    totalSpent DECIMAL(10,2) NOT NULL DEFAULT 0.0 CHECK (totalSpent >= 0),
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_loyalty_user FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE
);